Furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from users.views import dashboard, get_total_sales_by_month

urlpatterns = [
    path("",LoginView.as_view(template_name='users/login.html'),name="login"),
    path("logout",LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('category/',include('category.urls')),
    path('material/',include('material.urls')),
    path('OwnerPayment/',include('OwnerPayment.urls')),
    path('supplier/',include('supplier.urls')),
    path('customer/',include('customer.urls')),
    path('Employee/',include('employee.urls')),
    path('subcategory/',include('subcategory.urls')),
    path('customerpayment/',include('customerpayment.urls')),
    path('Supplierpayment/', include('Supplierpayment.urls')),
    path('product/',include('product.urls')),
    path('productin/',include('productin.urls')),
    path('productout/',include('productout.urls')),
    path('inward_purchase/', include('inward_purchase.urls')),
    path('outward_purchase/', include('outward_purchase.urls')),
    path('loss/', include('loss.urls')),
    path("dashboard/",dashboard,name="dashboard"),
    path("total_sales_by_month/",get_total_sales_by_month,name="total_sale_by_month")

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loss/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path("new/", NewLoss.as_view(), name="loss-new"),
    path("view/", ViewLoss.as_view(), name="loss-view"),
    path("update/<int:pk>", UpdateLoss.as_view(), name="loss-update"),
    path("delete/<int:pk>", DeleteLoss.as_view(), name="loss-delete")
]

loss/models.py
from django.db import models
from product.models import product
from datetime import datetime
from django.urls import reverse
# Create your models here.
class loss(models.Model):
    date = models.DateField(default=datetime.utcnow)
    product = models.ForeignKey(product, on_delete=models.CASCADE, related_name="loss")
    price = models.IntegerField()
    rate = models.IntegerField()
    quantity = models.IntegerField()
    remark = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.id}-{self.product}"

    def get_absolute_url(self):
        return reverse("loss-view")

loss/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from productin.models import prodcutin
from .models import loss
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class NewLoss(LoginRequiredMixin,CreateView):
    model = loss
    fields = '__all__'

    def form_valid(self, form):
        print("inside  form valid before save")
        self.object = form.save()
        print("inside  form valid")
        self.object.product.quantity = self.object.product.quantity - self.object.quantity
        self.object.product.save()
        self.object.save()
        print("object is saved")
        return HttpResponseRedirect(self.get_success_url())


class ViewLoss(LoginRequiredMixin,ListView):
    model = loss
    context_object_name = 'losses'


class UpdateLoss(LoginRequiredMixin,UpdateView):
    model = loss
    fields = '__all__'

    def form_valid(self, form):
        print("inside  form valid before save")
        self.object = form.save()
        print("inside  form valid")
        self.object.product.quantity = self.object.product.quantity - self.object.quantity
        self.object.product.save()
        self.object.save()
        print("object is saved")
        return HttpResponseRedirect(self.get_success_url())


class DeleteLoss(LoginRequiredMixin,DeleteView):
    model = loss
    success_url = '/loss/view'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.product.quantity = self.object.product.quantity + self.object.quantity
        self.object.product.save()
        return super(DeleteLoss, self).delete(request, *args, **kwargs)

loss/templates/loss/loss_confirm_delete.html
{% extends "users/layout.html" %}
{% load static  %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css'%}">

{% endblock %}
{% block header_title %}
    Loss Delete
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Loss</a></li>
              <li class="breadcrumb-item active">Delete </li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-danger">
              <div class="card-header">
                <h3 class="card-title">Are you sure you want to delete ? </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <ul>
                  <li> Date : {{ object.date}}</li>
                  <li> Product : {{ object.product.name }}</li>
                  <li>Remarks : {{ object.remark | safe }}</li>
              </ul>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-danger">Delete</button>
                  <a href="{% url 'loss-view' %}" class="btn btn-info">Cancel</a>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

loss/templates/loss/loss_form.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css'%}">

{% endblock %}
{% block header_title %}
    Loss Entry
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Loss</a></li>
              <li class="breadcrumb-item active">New</li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">New Loss Product Form </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="post">
                  {% csrf_token %}
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="name">Date </label>
                                {% crispy_field form.date  %}
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="name">Product Id </label>
                                {% crispy_field form.product  %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="name">Rate </label>
                                {% crispy_field form.rate  %}
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="name">Quantity </label>
                                {% crispy_field form.quantity %}
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="name">Price </label>
                                {% crispy_field form.price %}
                            </div>
                        </div>
                    </div>

                  <div class="form-group">
                    <label for="description">Remarks </label>
                    {% crispy_field form.remark %}

                  </div>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}
{% block extra_js %}
    <!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js'%}"></script>
<script>
  $(function () {
    // Summernote
    $('#id_remark').summernote()
  })

  document.addEventListener('DOMContentLoaded',function() {

             // for rate
             document.querySelector("#id_rate").focusout = function () {
                 let qty = document.querySelector("#id_quantity").value;
                 let rate = document.querySelector("#id_rate").value;
                 document.querySelector("#id_price").value = rate * qty;

             }
         })
</script>

{% endblock %}

loss/templates/loss/loss_list.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
 <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/searchbuilder/1.1.0/css/searchBuilder.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/datetime/1.1.0/css/dataTables.dateTime.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/colreorder/1.5.4/css/colReorder.dataTables.min.css">
{% endblock %}
{% block header_title %}
    Loss Product View
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Loss Product</a></li>
              <li class="breadcrumb-item active">View</li>
            </ol>
{% endblock %}
{% block body%}
  <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">


            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Loss Product Reports</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                   {% for cate in losses %}
                       <tr>
                       <td> {{ cate.id }}</td>
                       <td>{{ cate.date }}</td>
                       <td>{{ cate.product.name}}</td>
                        <td>{{ cate.price }}</td>
                       <td><a class="btn btn-outline-info btn-sm" href="{% url 'loss-update' cate.id %}">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Edit
                          </a>
                        <a class="btn btn-outline-danger btn-sm" href="{% url 'loss-delete' cate.id %}">
                              <i class="fas fa-trash">
                              </i>
                              Delete
                          </a>
                       </td>

                       </tr>
                   {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                   <th>ID</th>
                     <th>Date</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Action</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}
{% block extra_js %}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/colreorder/1.5.4/js/dataTables.colReorder.min.js"></script>
    <script src="https://cdn.datatables.net/searchbuilder/1.1.0/js/dataTables.searchBuilder.min.js"></script>
    <script src="https://cdn.datatables.net/datetime/1.1.0/js/dataTables.dateTime.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.colVis.min.js"></script>


    <script>
    $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'QBfrtip',
        colReorder: true,
        buttons: [
            'colvis',
            'copy',
            {
                extend: 'excel',
                messageTop: 'PDF created by PDFMake with Buttons for DataTables.',
                exportOptions: {
                    columns: ':visible'
                }
            },
            {
                extend: 'pdfHtml5',
                messageTop: 'SunShine Furniture Mart',
                exportOptions: {
                    columns: ':visible'
                }
            },
              {
                    extend: 'print',
                    exportOptions:{
                    columns:':visible'
                    }
            }
        ]
    } );
} );
    </script>
     <script src="{% static '/dist/js/adminlte.js'%}"></script>

{% endblock %}