Furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from users.views import dashboard, get_total_sales_by_month

urlpatterns = [
    path("",LoginView.as_view(template_name='users/login.html'),name="login"),
    path("logout",LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('category/',include('category.urls')),
    path('material/',include('material.urls')),
    path('OwnerPayment/',include('OwnerPayment.urls')),
    path('supplier/',include('supplier.urls')),
    path('customer/',include('customer.urls')),
    path('Employee/',include('employee.urls')),
    path('subcategory/',include('subcategory.urls')),
    path('customerpayment/',include('customerpayment.urls')),
    path('Supplierpayment/', include('Supplierpayment.urls')),
    path('product/',include('product.urls')),
    path('productin/',include('productin.urls')),
    path('productout/',include('productout.urls')),
    path('inward_purchase/', include('inward_purchase.urls')),
    path('outward_purchase/', include('outward_purchase.urls')),
    path('loss/', include('loss.urls')),
    path("dashboard/",dashboard,name="dashboard"),
    path("total_sales_by_month/",get_total_sales_by_month,name="total_sale_by_month")

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customerpayment/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path("new/", NewCustomerPayment.as_view(), name="Customerpayment-new"),
    path("view/", ViewCustomerPayment.as_view(), name="Customerpayment-view"),
    path("update/<int:pk>", UpdateCustomerPayment.as_view(), name="Customerpayment-update"),
    path("delete/<int:pk>", DeleteCustomerPayment.as_view(), name="Customerpayment-delete"),
    path("detail/<int:pk>",DetailCustomerPayment.as_view(),name="Customerpayment-detail"),
    path("invoice/<int:billid>",invoice, name="printbill")

]

loss/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path("new/", NewLoss.as_view(), name="loss-new"),
    path("view/", ViewLoss.as_view(), name="loss-view"),
    path("update/<int:pk>", UpdateLoss.as_view(), name="loss-update"),
    path("delete/<int:pk>", DeleteLoss.as_view(), name="loss-delete")
]

customerpayment/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from outward_purchase.models import outward_purchase
from django.core.validators import MinValueValidator
from customer.models import customer
# Create your models here.
class customerpay(models.Model):
    choice = (
        ('cash','cash'), ('netbank','netbank'), ('upi','upi'), ('cheque', 'cheque')
    )
    type = models.CharField(max_length=80, choices=choice,default='')
    bank_name = models.CharField(max_length=80, null=True, blank=True,default='')
    bank_branch = models.CharField(max_length=400, null=True, blank=True,default='')
    account_no = models.CharField(max_length=80, null=True, blank=True,default='')
    ifsc_code = models.CharField(max_length=80, null=True, blank=True,default='')
    phone = models.CharField(max_length=15, null=True, blank=True,default='')
    upi = models.CharField(max_length=80, null=True, blank=True,default='')
    cash = models.IntegerField(default=0, null=True, blank=True,validators=[MinValueValidator(0,'Value should not be less than 0')])
    check_no = models.CharField(max_length=30, default='', null=True, blank=True)
    check_date = models.CharField(max_length=35, default='', null=True, blank=True)
    date = models.DateField(default=datetime.utcnow())
    bill = models.ForeignKey(outward_purchase, on_delete=models.CASCADE, related_name='bills', default='')


    def __str__(self):
        return f"{self.cash}"

    def get_absolute_url(self):
        return reverse("Customerpayment-view")

customerpayment/views.py
from django.shortcuts import render
from django.views.generic import CreateView,ListView,UpdateView,DeleteView,DetailView
from .models import *
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
class NewCustomerPayment(LoginRequiredMixin,CreateView):
    model = customerpay
    fields = '__all__'

    def form_valid(self, form):
        self.object = form.save()
        self.object.bill.due_amount = self.object.bill.net_amount - self.object.cash
        if self.object.bill.due_amount < 0:
            self.object.bill.due_amount = self.object.bill.net_amount
            self.object.delete()
            return HttpResponseRedirect('/Customerpayment/new/')
        else:
            self.object.bill.save()
            return HttpResponseRedirect(self.get_success_url())
class ViewCustomerPayment(LoginRequiredMixin,ListView):
    model = customerpay
    context_object_name = 'customerpay'

class UpdateCustomerPayment(LoginRequiredMixin,UpdateView):
    model = customerpay
    fields = '__all__'

class DeleteCustomerPayment(LoginRequiredMixin,DeleteView):
    model = customerpay
    success_url = '/Customerpayment/view'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.bill.due_amount = self.object.bill.due_amount + self.object.cash
        self.object.bill.save()
        return super(DeleteCustomerPayment, self).delete(request, *args, **kwargs)

class DetailCustomerPayment(LoginRequiredMixin,DetailView):
    model = customerpay

def invoice(request,billid):
    object = customerpay.objects.get(id=billid)
    return render(request, "customerpayment/customerpay_print.html", {
        "object": object
    })

customerpayment/templates/customerpayment/customerpay_confirm_delete.html
{% extends "users/layout.html" %}
{% load static  %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css'%}">

{% endblock %}
{% block header_title %}
   Customer Payment Option Delete
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Customer Payment</a></li>
              <li class="breadcrumb-item active">Delete </li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-danger">
              <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash">
                    Are you sure you want to delete ?
                    </i>
                </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <ul>
                      <li> Type : {{ object.type }}</li>
                      <li> Date : {{ object.date }}</li>
                      <li> Outward Bill : {{ object.bill }}</li>
                      <li> Customer Name: {{ object.cus.first_name }} {{ object.cus.last_name }}</li>
                      <li> Balance : {{ object.cash }}</li>
              </ul>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-danger">Delete</button>
                  <a href="{% url 'Customerpayment-view' %}" class="btn btn-info">Cancel</a>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

customerpayment/templates/customerpayment/customerpay_detail.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

{% endblock %}
{% block header_title %}
    Payment Detail
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Customer Payment</a></li>
              <li class="breadcrumb-item active">detail</li>
            </ol>
{% endblock %}
{% block body%}
<div class="card card-solid">
        <div class="card-body pb-0">
          <div class="row d-flex align-items-stretch">
            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
              <div class="card bg-light">
                <div class="card-header text-muted border-bottom-0">
                  Customer ID : {{ object.id }}
                </div>
                <div class="card-body pt-0">
                  <div class="row">
                    <div class="col-7">
                      <h4 class="lead"> <b>Name : {{object.bill.cus.firstname}} {{ object.bill.cus.lastname }} </b></h4>
                      <p class="lead"><b>Due Payment :</b> {{ object.bill.due_amount }}₹</p>
                      <p class="lead"><b>Total Amount :</b> {{ object.bill.net_amount }}₹</p>
                      <ul class="ml-4 mb-0 fa-ul text-muted">
                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span>
                            Address: {{ object.bill.cus.house_no }} {{object.bill.cus.streetname}}
                                     {{ object.bill.cus.areaname }} {{ object.bill.cus.city }}
                        </li>
                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone : {{ object.bill.cus.phoneno }}</li>
                      </ul>
                    </div>
                    <div class="col-5 text-center">
                      <img src="{% static 'dist/img/elegant-furniture-logo-with-lamp_23-2148477392.jpg' %}" alt="user-avatar" class="img-circle img-fluid">
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <div class="text-right">
                    <a href="{% url 'printbill' object.id %}" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                  </div>
                </div>
              </div>
            </div>
            </div>
        </div>
</div>
{% endblock %}
{% block extra_js %}
{% endblock %}

customerpayment/templates/customerpayment/customerpay_form.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css'%}">

{% endblock %}
{% block header_title %}
    Customer Payment Detail Entry
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Customer Payment Detail</a></li>
              <li class="breadcrumb-item active">Add</li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">New Customer Payment Detail Form </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="post">
                  {% csrf_token %}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">Bill Payment Date</label>
                        {% crispy_field form.date %}
                     </div>
                     <div class="form-group">
                        <label for="name">Please Select Bill</label>
                        {% crispy_field form.bill %}
                     </div>
                     <div class="form-group" id="type">
                        <label for="name">Please Select Type Of Payment</label>
                        {% crispy_field form.type %}
                     </div>
                     <div class="form-group" id="cash">
                        <label for="name">Amount</label>
                        {% crispy_field form.cash %}
                     </div>
                     <div class="form-group" id="bank">
                        <label for="name">Bank Name</label>
                        {% crispy_field form.bank_name %}
                     </div>
                     <div class="form-group" id="bank1">
                        <label for="name">Bank Branch</label>
                        {% crispy_field form.bank_branch %}
                     </div>
                     <div class="form-group" id="bank2">
                        <label for="name">Account Number</label>
                        {% crispy_field form.account_no %}
                     </div>
                     <div class="form-group" id="bank3">
                        <label for="name">IFSC code</label>
                        {% crispy_field form.ifsc_code %}
                     </div>
                     <div class="form-group" id="upi">
                        <label for="name">Phone Number</label>
                        {% crispy_field form.phone %}
                     </div>
                     <div class="form-group" id="upi1">
                        <label for="name">UPI ID</label>
                        {% crispy_field form.upi %}
                     </div>
                     <div class="form-group" id="check">
                        <label for="name">Cheque Number</label>
                        {% crispy_field form.check_no %}
                     </div>

                     <div class="form-group" id="check1">
                        <label>Cheque Date</label>
                         {% crispy_field form.check_date %}
                     </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

    <script>
    document.addEventListener('DOMContentLoaded',function (){
        document.querySelector("#id_type").onchange=function(){
            console.log("inside onchange ")
            if(this.value==='cash'){
                document.querySelector("#cash").style.display="block"
                document.querySelector("#bank").style.display="none"
                document.querySelector("#bank1").style.display="none"
                document.querySelector("#bank2").style.display="none"
                document.querySelector("#bank3").style.display="none"
                document.querySelector("#check").style.display="none"
                document.querySelector("#check1").style.display="none"
                document.querySelector("#upi").style.display="none"
                document.querySelector("#upi1").style.display="none"
            }
            else if (this.value==='upi'){
                document.querySelector("#cash").style.display="block"
                document.querySelector("#bank").style.display="none"
                document.querySelector("#bank1").style.display="none"
                document.querySelector("#bank2").style.display="none"
                document.querySelector("#bank3").style.display="none"
                document.querySelector("#check").style.display="none"
                document.querySelector("#check1").style.display="none"
                document.querySelector("#upi").style.display="block"
                document.querySelector("#upi1").style.display="block"
            }
            else if(this.value==='cheque'){
                document.querySelector("#cash").style.display="block"
                document.querySelector("#bank").style.display="none"
                document.querySelector("#bank1").style.display="none"
                document.querySelector("#bank2").style.display="none"
                document.querySelector("#bank3").style.display="none"
                document.querySelector("#check").style.display="block"
                document.querySelector("#check1").style.display="block"
                document.querySelector("#upi").style.display="none"
                document.querySelector("#upi1").style.display="none"
            }
            else if(this.value==='netbank'){
                document.querySelector("#cash").style.display="block"
                document.querySelector("#bank").style.display="block"
                document.querySelector("#bank1").style.display="block"
                document.querySelector("#bank2").style.display="block"
                document.querySelector("#bank3").style.display="block"
                document.querySelector("#check").style.display="none"
                document.querySelector("#check1").style.display="none"
                document.querySelector("#upi").style.display="none"
                document.querySelector("#upi1").style.display="none"

            }
        }
    })
    </script>

{% endblock %}
{% block extra_js %}
    <!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js'%}"></script>
<script>
  $(function () {
    // Summernote
    $('#id_description').summernote()


  })
</script>
{% endblock %}

customerpayment/templates/customerpayment/customerpay_list.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
 <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/searchbuilder/1.1.0/css/searchBuilder.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/datetime/1.1.0/css/dataTables.dateTime.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/colreorder/1.5.4/css/colReorder.dataTables.min.css">
{% endblock %}
{% block header_title %}
    Customer Payment Details
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Customer Payment</a></li>
              <li class="breadcrumb-item active">View</li>
            </ol>
{% endblock %}
{% block body%}
  <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">


            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Payment Methods</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>ID</th>
                      <th>Type</th>
                      <th>Date</th>
                      <th>Outward Bill</th>
                      <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                   {% for pay in customerpay %}
                       <tr>
                           <td> {{ pay.id }}</td>
                           <td>{{ pay.type }}</td>
                           <td>{{ pay.date }}</td>
                           <td>{{ pay.bill.id }}</td>
                           <td><a class="btn btn-outline-info btn-sm" href="{% url 'Customerpayment-update' pay.id %}">
                                  <i class="fas fa-pencil-alt">
                                  </i>
                                  Edit
                              </a>
                            <a class="btn btn-outline-success btn-sm" href="{% url 'Customerpayment-detail' pay.id %}">
                                  <i class="fas fa-search-alt">
                                  </i>
                                  Detail
                              </a>
                            <a class="btn btn-outline-danger btn-sm" href="{% url 'Customerpayment-delete' pay.id %}">
                                  <i class="fas fa-trash">
                                  </i>
                                  Delete
                              </a>
                           </td>

                       </tr>
                   {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                      <th>ID</th>
                      <th>Type</th>
                      <th>Date</th>
                      <th>Outward Bill</th>
                      <th>Action</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}
{% block extra_js %}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/colreorder/1.5.4/js/dataTables.colReorder.min.js"></script>
    <script src="https://cdn.datatables.net/searchbuilder/1.1.0/js/dataTables.searchBuilder.min.js"></script>
    <script src="https://cdn.datatables.net/datetime/1.1.0/js/dataTables.dateTime.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.colVis.min.js"></script>


    <script>
    $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'QBfrtip',
        colReorder: true,
        buttons: [
            'colvis',
            'copy',
            {
                extend: 'excel',
                messageTop: 'PDF created by PDFMake with Buttons for DataTables.',
                exportOptions: {
                    columns: ':visible'
                }
            },
            {
                extend: 'pdfHtml5',
                messageTop: 'SunShine Furniture Mart',
                exportOptions: {
                    columns: ':visible'
                }
            },
              {
                    extend: 'print',
                    exportOptions:{
                    columns:':visible'
                    }
            }
        ]
    } );
} );
    </script>
     <script src="{% static '/dist/js/adminlte.js'%}"></script>

{% endblock %}

customerpayment/templates/customerpayment/customerpay_print.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

{% endblock %}
{% block header_title %}
    Payment Detail
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Customer Payment</a></li>
              <li class="breadcrumb-item active">detail</li>
            </ol>
{% endblock %}
{% block body%}
<div class="card card-solid">
        <div class="card-body pb-0">
          <div class="row d-flex align-items-stretch">
            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
              <div class="card bg-light">
                <div class="card-header text-muted border-bottom-0">
                  Customer ID : {{ object.id }}
                </div>
                <div class="card-body pt-0">
                  <div class="row">
                    <div class="col-7">
                      <h3 class="lead"><b> {{object.bill.cus.firstname}} {{ object.bill.cus.lastname }}</b></h3>
                      <p class="text-muted text-sm"><b>Due Payment :</b> {{ object.bill.due_amount }}₹</p>
                      <p class="text-muted text-sm"><b>Total Amount :</b> {{ object.bill.net_amount }}₹</p>
                      <ul class="ml-4 mb-0 fa-ul text-muted">
                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span>
                            Address: {{ object.bill.cus.house_no }} {{object.bill.cus.streetname}}
                                     {{ object.bill.cus.areaname }} {{ object.bill.cus.city }}
                        </li>
                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone : {{ object.bill.cus.phoneno }}</li>
                      </ul>
                    </div>
                    <div class="col-5 text-center">
                      <img src="{% static 'dist/img/elegant-furniture-logo-with-lamp_23-2148477392.jpg' %}" alt="user-avatar" class="img-circle img-fluid">
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <div class="text-right">
                    <a href="{% url 'printbill' object.id %}"></a>
                  </div>
                </div>
              </div>
            </div>
            </div>
        </div>
</div>
{% endblock %}
{% block extra_js %}
    <script>
  window.addEventListener("load", window.print());
</script>
{% endblock %}