Furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from users.views import dashboard, get_total_sales_by_month

urlpatterns = [
    path("",LoginView.as_view(template_name='users/login.html'),name="login"),
    path("logout",LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('category/',include('category.urls')),
    path('material/',include('material.urls')),
    path('OwnerPayment/',include('OwnerPayment.urls')),
    path('supplier/',include('supplier.urls')),
    path('customer/',include('customer.urls')),
    path('Employee/',include('employee.urls')),
    path('subcategory/',include('subcategory.urls')),
    path('customerpayment/',include('customerpayment.urls')),
    path('Supplierpayment/', include('Supplierpayment.urls')),
    path('product/',include('product.urls')),
    path('productin/',include('productin.urls')),
    path('productout/',include('productout.urls')),
    path('inward_purchase/', include('inward_purchase.urls')),
    path('outward_purchase/', include('outward_purchase.urls')),
    path('loss/', include('loss.urls')),
    path("dashboard/",dashboard,name="dashboard"),
    path("total_sales_by_month/",get_total_sales_by_month,name="total_sale_by_month")

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loss/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path("new/", NewLoss.as_view(), name="loss-new"),
    path("view/", ViewLoss.as_view(), name="loss-view"),
    path("update/<int:pk>", UpdateLoss.as_view(), name="loss-update"),
    path("delete/<int:pk>", DeleteLoss.as_view(), name="loss-delete")
]

material/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path("new/",NewMaterial.as_view(),name="material-new"),
    path("view/",ViewMaterial.as_view(),name="material-view"),
    path("update/<int:pk>",UpdateMaterial.as_view(),name="material-update"),
    path("delete/<int:pk>",DeleteMaterial.as_view(),name="material-delete")
]

material/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class material(models.Model):
    name=models.CharField(max_length=80)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("material-view")

material/views.py
from django.shortcuts import render
from django.views.generic import CreateView,ListView,UpdateView,DeleteView
from .models import material
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class NewMaterial(LoginRequiredMixin,CreateView):
    model = material
    fields = '__all__'

class ViewMaterial(LoginRequiredMixin,ListView):
    model = material
    context_object_name = 'material'

class UpdateMaterial(LoginRequiredMixin,UpdateView):
    model = material
    fields = '__all__'

class DeleteMaterial(LoginRequiredMixin,DeleteView):
    model = material
    success_url = '/material/view'

material/templates/material/material_confirm_delete.html
{% extends "users/layout.html" %}
{% load static  %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css'%}">

{% endblock %}
{% block header_title %}
    Material Delete
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Category</a></li>
              <li class="breadcrumb-item active">Delete </li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-danger">
              <div class="card-header">
                <h3 class="card-title">Are you sure you want to delete ? </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <ul>
                  <li> Name : {{ object.name }}</li>
                  <li> Descrition : <br> {{ object.description | safe }}</li>
              </ul>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-danger">Delete</button>
                  <a href="{% url 'material-view' %}" class="btn btn-info">Cancel</a>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

material/templates/material/material_form.html
{% extends "users/layout.html" %}
{% load static %}
{% load crispy_forms_field %}
{% block extra_css %}
       <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css'%}">
{% endblock %}
{% block header_title %}Material entry{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Material</a></li>
              <li class="breadcrumb-item active">New</li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">New Material Form </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">Name </label>
                    {% crispy_field form.name  %}
                  </div>
                  <div class="form-group">
                    <label for="description">Descritpion </label>
                    {% crispy_field form.description %}
                  </div>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}
{% block extra_js %}
    <!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js'%}"></script>
<script>
  $(function () {
    // Summernote
    $('#id_description').summernote()

  })
</script>
{% endblock %}

material/templates/material/material_list.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
 <!-- DataTables -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
 <link rel="stylesheet" href="https://cdn.datatables.net/searchbuilder/1.1.0/css/searchBuilder.dataTables.min.css">
 <link rel="stylesheet" href="https://cdn.datatables.net/datetime/1.1.0/css/dataTables.dateTime.min.css">
{% endblock %}
{% block header_title %}
    Material View
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Material</a></li>
              <li class="breadcrumb-item active">View</li>
            </ol>
{% endblock %}
{% block body%}
  <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">


            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Material Records</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                   {% for mat in material %}
                       <tr>
                       <td>{{ mat.id }}</td>
                       <td>{{ mat.name }}</td>
                       <td>{{ mat.description | safe}}</td>
                       <td><a class="btn btn-outline-info btn-sm" href="{% url 'material-update' mat.id %}">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Edit
                          </a>
                        <a class="btn btn-outline-danger btn-sm" href="{% url 'material-delete' mat.id %}">
                              <i class="fas fa-trash">
                              </i>
                              Delete
                          </a>
                       </td>
                       </tr>
                   {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                   <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Action</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}
{% block extra_js %}
    <!-- Page specific script -->
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/searchbuilder/1.1.0/js/dataTables.searchBuilder.min.js"></script>
<script src="https://cdn.datatables.net/datetime/1.1.0/js/dataTables.dateTime.min.js"></script>


    <!-- Page specific script -->
<script>
  $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Qlfrtip'
    });
});
</script>
{% endblock %}