Furniture/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from users.views import dashboard, get_total_sales_by_month

urlpatterns = [
    path("",LoginView.as_view(template_name='users/login.html'),name="login"),
    path("logout",LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('category/',include('category.urls')),
    path('material/',include('material.urls')),
    path('OwnerPayment/',include('OwnerPayment.urls')),
    path('supplier/',include('supplier.urls')),
    path('customer/',include('customer.urls')),
    path('Employee/',include('employee.urls')),
    path('subcategory/',include('subcategory.urls')),
    path('customerpayment/',include('customerpayment.urls')),
    path('Supplierpayment/', include('Supplierpayment.urls')),
    path('product/',include('product.urls')),
    path('productin/',include('productin.urls')),
    path('productout/',include('productout.urls')),
    path('inward_purchase/', include('inward_purchase.urls')),
    path('outward_purchase/', include('outward_purchase.urls')),
    path('loss/', include('loss.urls')),
    path("dashboard/",dashboard,name="dashboard"),
    path("total_sales_by_month/",get_total_sales_by_month,name="total_sale_by_month")

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inward_purchase/urls.py
from django.urls import path
from .views import *
urlpatterns=[
        path("new/", NewInwardBill.as_view(), name="new-purchase"),
        path("closed/", closewindow, name="closed"),
        path("view/", ViewPurchaseBill.as_view(), name="view-purchase"),
        path("update/<int:pk>", UpdatePurchaseBill.as_view(), name="update-purchase"),
        path("delete/<int:pk>", DeletePurchaseBill.as_view(), name="delete-purchase"),
        path("detail/<int:pk>", DetailPurchaseBill.as_view(), name="detail-purchase"),
        path("invoice/<int:billid>",invoice, name="print")
]

loss/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path("new/", NewLoss.as_view(), name="loss-new"),
    path("view/", ViewLoss.as_view(), name="loss-view"),
    path("update/<int:pk>", UpdateLoss.as_view(), name="loss-update"),
    path("delete/<int:pk>", DeleteLoss.as_view(), name="loss-delete")
]

inward_purchase/models.py
from django.db import models
from datetime import datetime
from productin.models import prodcutin
from supplier.models import supplier
from django.urls import reverse

# Create your models here.

class inward_purchase(models.Model):
    date = models.DateField(default=datetime.utcnow)
    spp = models.ForeignKey(supplier, on_delete=models.CASCADE, related_name="suppliers",default='')
    products = models.ManyToManyField(prodcutin, related_name='inward_purchase_bill')
    total = models.IntegerField()
    gst = models.DecimalField(default=0,max_digits=9, decimal_places=2)
    cgst=models.DecimalField(default=0,max_digits=9,decimal_places=2)
    discount = models.DecimalField(default=0,max_digits=9, decimal_places=2, blank=True, null=True)
    net_amount = models.DecimalField(max_digits=9, decimal_places=2)
    due_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return f"{self.id}"

    def get_absolute_url(self):
        return reverse('view-purchase')

inward_purchase/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from productin.models import prodcutin
from django import forms
from .models import inward_purchase
from django.views.generic import CreateView,ListView,DetailView,DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class NewInwardBill(LoginRequiredMixin,CreateView):
    model = inward_purchase
    fields = ['date','spp','total','net_amount','gst','cgst','discount','due_amount']
    success_url = '/inward_purchase/view'

    def get_context_data(self, **kwargs):
        from django.db.models import Sum
        from django.db.models import aggregates
        context = super().get_context_data(**kwargs)
        context["products"] = prodcutin.objects.filter(is_billed=False).all()
        result = prodcutin.objects.filter(is_billed=False).aggregate(Sum('price'))
        context["to"] = result['price__sum']
        return context

    def form_valid(self, form):
        print("inside  form valid before save")
        self.object = form.save()
        print("inside  form valid")
        for product in prodcutin.objects.filter(is_billed=False).all():
            self.object.products.add(product)
            product.productname.qun = int(product.productname.qun) + int(product.qun)
            product.productname.save()
            product.is_billed = True
            product.save()

        self.object.save()
        print("object is saved")
        return HttpResponseRedirect(self.get_success_url())


class ViewPurchaseBill(LoginRequiredMixin,ListView):
    model = inward_purchase
    context_object_name = "bills"

class UpdatePurchaseBill(LoginRequiredMixin,UpdateView):
    model = inward_purchase
    fields = ['date', 'spp', 'total', 'net_amount', 'gst','cgst' ,'discount', 'due_amount']
    success_url = '/inward_purchase/view'

    def get_context_data(self, **kwargs):
        from django.db.models import Sum
        from django.db.models import aggregates
        context = super().get_context_data(**kwargs)
        context["products"] = self.object.products.all() | prodcutin.objects.filter(is_billed=False).all()
        result = prodcutin.objects.filter(is_billed=False).aggregate(Sum('price'))
        if result['price__sum'] == None:
            context["to"] = self.object.total
        else:
            context["to"] = self.object.total + result['price__sum']
        return context

    def form_valid(self, form):
        print("inside  form valid before save")
        self.object = form.save()
        print("inside  form valid")
        for product in prodcutin.objects.filter(is_billed=False).all():
            self.object.products.add(product)
            product.productname.qun = int(product.productname.qun) + int(product.qun)
            product.productname.save()
            product.is_billed = True
            product.save()

        self.object.save()
        print("object is saved")
        return HttpResponseRedirect(self.get_success_url())
class DeletePurchaseBill(LoginRequiredMixin,DeleteView):
    model = inward_purchase
    success_url = '/inward_purchase/view'

    def delete(self, request, *args, **kwargs):
        print("inside  form valid before save")
        print("inside  form valid")
        self.object = self.get_object()
        for product in self.object.products.all():
            print(product.productname.name)
            product.productname.qun = int(product.productname.qun) - int(product.qun)
            product.productname.save()
            product.save()
        return super(DeletePurchaseBill, self).delete(request, *args, **kwargs)


class DetailPurchaseBill(LoginRequiredMixin,DetailView):
    model = inward_purchase

def closewindow(request):
    return render(request,"inward_purchase/close_window.html")

def invoice(request,billid):
    object = inward_purchase.objects.get(id=billid)
    return render(request, "inward_purchase/invoice_print.html", {
        "object": object
    })

inward_purchase/templates/inward_purchase/close_window.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script>
        //window.parent.
        //parent.location.reload();
        window.opener.location.reload(false);
        window.close();

        //window.location.reload();

    </script>
</head>
<body>

</body>
</html>

inward_purchase/templates/inward_purchase/invoice_print.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

{% endblock %}
{% block header_title %}
    Inward Invoice
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Inward Invoice</a></li>
              <li class="breadcrumb-item active">detail</li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main Sidebar Container -->

     <!-- Content Wrapper. Contains page content -->
  <div class="col-12">
    <!-- Content Header (Page header) -->


    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">


            <!-- Main content -->
            <div class="invoice p-3 mb-3">
              <!-- title row -->
              <div class="row">
                <div class="col-12">
                  <h4>
                    <i class="fas fa-chair"></i> <strong> Sunshine Furniture Mart </strong>
                    <small class="float-right">Date:{{ object.date }} </small>
                  </h4>
                </div>
                <!-- /.col -->
              </div>
              <!-- info row -->
              <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                  From
                  <address>
                    <strong>Company Name:{{ object.spp.companyname }}</strong><br>
                      <strong>Name: {{ object.spp.firstname }}{{ object.spp.lastname }}</strong><br>
                      {{ object.spp.house_nono }} {{ object.spp.streetname }}<br>
                      {{ object.spp.areaname }} {{ object.spp.city }}<br>
                      {{ object.spp.state }} {{ object.spp.country }}<br>
                      {{ object.spp.pincode }}<br>
                    Phone: {{ object.spp.phoneno }}<br>
                    Email: {{ object.spp.email }}
                  </address>

                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  To
                  <address>
                    <strong>Sunshine Furniture Mart</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (555) 539-1037<br>
                    Email: john.doe@example.com
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  <b>Invoice {{ object.id }}</b><br>
                    <b>Payment Due:</b> {{ object.due_amount }}<br>
                  <b>Account:</b> {{ object.id }}
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- Table row -->
              <div class="row">
                <div class="col-12 table-responsive">
                 <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                      <th>Rate</th>
                      <th>Price</th>
                      <th>Discount</th>
                      <th>GST</th>
                  </tr>
                  </thead>
                  <tbody>
                   {% for mat in  object.products.all  %}
                       <tr>
                       <td> {{ mat.id }}</td>
                       <td>{{ mat.productname }}</td>
                       <td>{{ mat.qun}}</td>
                           <td>{{ mat.rate }}</td>
                           <td>{{ mat.price }}</td>
                           <td>{{ mat.discount }}</td>
                           <td>{{ mat.GSTno  }}</td>
                       </tr>
                   {% endfor %}
                  </tbody>

                </table>

                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <div class="row">
                <!-- accepted payments column -->
                <div class="col-6">
                  <p class="lead">We're counting our blessings and that means Suppliers like you.</p>
                  <p class="lead" style="margin-top: 10px;">
                    Thankyou Visit Again!.
                    <br style="font-size: 10px">No-Refund Policy
                    <br>No Exchange Policy
                  </p>
                </div>
                <!-- /.col -->
                <div class="col-6">
                  <p class="lead">{{ object.date }}</p>

                  <div class="table-responsive">
                    <table class="table">
                      <tr>
                        <th style="width:50%">Subtotal:</th>
                        <td>{{ object.net_amount }}₹</td>
                      </tr>
                      <tr>
                        <th>GST Tax</th>
                        <td>{{object.gst}}₹</td>
                      </tr>
                      <tr>
                        <th>Disscount</th>
                        <td>{{object.discount}}₹</td>
                      </tr>
                      <tr>
                        <th>Total:</th>
                        <td>{{ object.total }}₹</td>
                      </tr>
                    </table>
                  </div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- this row will not appear when printing -->
              <div class="row no-print">
                <div class="col-12">
                  <a href="{% url 'print' object.id %}" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                    <a href="{% url 'supplierpay-new' %}"><button type="button" class="btn btn-success float-right"><i class="far fa-credit-card"></i> Submit Payment
                  </button></a>

                </div>
              </div>
            </div>
            <!-- /.invoice -->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}
{% block extra_js %}
    <script>
  window.addEventListener("load", window.print());
</script>
{% endblock %}

inward_purchase/templates/inward_purchase/inward_purchase_confirm_delete.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

{% endblock %}
{% block header_title %}
    Inward Purchase Bill Delete
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Inward Purchase Bill</a></li>
              <li class="breadcrumb-item active">delete</li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-danger">
              <div class="card-header">
                <h3 class="card-title">Are you sure you want to delete ? </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <ul>
                  <li> Suppier Name : {{ object.spp }} </li>
                  <li> Net Amount : {{ object.net_amount}}</li>
                  <li> Due Amount :{{ object.due_amount}}</li>
              </ul>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-danger">Delete</button>
                  <a href="{% url 'view-purchase' %}" class="btn btn-info">Cancel</a>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

inward_purchase/templates/inward_purchase/inward_purchase_detail.html
{% extends "users/layout.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block extra_css %}
     <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

{% endblock %}
{% block header_title %}
    Purchase Bill
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Purchase Bill</a></li>
              <li class="breadcrumb-item active">detail</li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main Sidebar Container -->

     <!-- Content Wrapper. Contains page content -->
  <div class="col-12">
    <!-- Content Header (Page header) -->


    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">



            <!-- Main content -->
            <div class="invoice p-3 mb-3">
              <!-- title row -->
              <div class="row">
                <div class="col-12">
                  <h4>
                    <i class="fas fa-chair"></i> <strong>Sunshine Furniture Mart </strong>
                    <small class="float-right">Date:{{ object.date }} </small>
                  </h4>
                </div>
                <!-- /.col -->
              </div>
              <!-- info row -->
              <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                  From

                  <address>
                    <strong>Company Name:{{ object.spp.companyname }}</strong><br>
                      <strong>Name: {{ object.spp.firstname }}{{ object.spp.lastname }}</strong><br>
                      {{ object.spp.house_nono }} {{ object.spp.streetname }}<br>
                    {{ object.spp.areaname }} {{ object.spp.city }}<br>
                    {{ object.spp.state }} {{ object.spp.country }}<br>
                   {{ object.spp.pincode }}<br>
                    Phone: {{ object.spp.phoneno }}<br>
                    Email: {{ object.spp.email }}
                  </address>

                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  To
                  <address>
                    <strong>Sunshine Furniture Mart</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (555) 539-1037<br>
                    Email: john.doe@example.com
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  <b>Invoice {{ object.id }}</b><br>
                    <b>Payment Due:</b> {{ object.due_amount }}<br>
                  <b>Account:</b> {{ object.id }}
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- Table row -->
              <div class="row">
                <div class="col-12 table-responsive">
                 <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                      <th>Rate</th>
                      <th>Price</th>
                      <th>Discount%</th>
                      <th>GST</th>
                  </tr>
                  </thead>
                  <tbody>
                   {% for mat in  object.products.all  %}
                       <tr>
                       <td> {{ mat.id }}</td>
                       <td>{{ mat.productname }}</td>
                       <td>{{ mat.qun}}</td>
                           <td>{{ mat.rate }}</td>
                           <td>{{ mat.price }}</td>
                           <td>{{ mat.discount }}</td>
                           <td>{{ mat.GSTno  }}</td>
                       </tr>
                   {% endfor %}
                  </tbody>

                </table>

                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <div class="row">
                <!-- accepted payments column -->
                <div class="col-6">
                  <p class="lead">We're counting our blessings and that means Suppliers like you.</p>
                  <p class="lead" style="margin-top: 10px;">
                    Thankyou Visit Again!.
                    <br style="font-size: 10px">No-Refund Policy
                    <br>No Exchange Policy
                  </p>
                </div>
                <!-- /.col -->
                <div class="col-6">
                  <p class="lead">{{ object.date }}</p>

                  <div class="table-responsive">
                    <table class="table">
                      <tr>
                        <th style="width:50%">Subtotal:</th>
                        <td>{{ object.net_amount }}₹</td>
                      </tr>
                      <tr>
                        <th>GST Tax</th>
                        <td>{{object.gst}}₹</td>
                      </tr>
                      <tr>
                        <th>Disscount</th>
                        <td>{{object.discount}}₹</td>
                      </tr>
                      <tr>
                        <th>Total:</th>
                        <td>{{ object.total }}₹</td>
                      </tr>
                    </table>
                  </div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- this row will not appear when printing -->
              <div class="row no-print">
                <div class="col-12">
                  <a href="{% url 'print' object.id %}" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                    <a href="{% url 'supplierpay-new' %}"><button type="button" class="btn btn-success float-right"><i class="far fa-credit-card"></i> Submit Payment
                  </button></a>

                </div>
              </div>
            </div>
            <!-- /.invoice -->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}
{% block extra_js %}
{% endblock %}

inward_purchase/templates/inward_purchase/inward_purchase_form.html
{% extends "users/layout.html" %}
{% load static %}
{% load crispy_forms_field %}
{% block extra_css %}

{% endblock %}
{% block header_title %}Product Purchase Inward Bill Entry{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Product Purchase Inward Bill</a></li>
              <li class="breadcrumb-item active">New</li>
            </ol>
{% endblock %}
{% block body%}
     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col">


              <!-- jquery validation -->

              <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Product Purchase Inward Bill Form </h3>
              </div>
              <!-- /.card-header -->

              <!-- form start -->
              <form id="quickForm"  method="post">
                  {% csrf_token %}
                <div class="card-body">

                 <div class="row">
                    <div class="col-4">
                            <div class="form-group">
                            <label for="name">Bill Date </label>
                            {% crispy_field form.date  %}
                          </div>
                    </div>
                     <div class="col-4">
                            <div class="form-group">
                            <label for="name">Supplier </label>
                            {% crispy_field form.spp  %}
                          </div>
                    </div>
                     <div class="col-4">
                           <div class="form-group">
                                <a href="{% url 'prodinward-new' %}" onclick="return !window.open(this.href, 'product update', 'width=700,height=600')"
                                     target="_blank"> Add Product </a>

                          </div>
                     </div>
                 </div>

                    <div class="form-group" >
                        <label for="description"> Amount</label>
                        {% crispy_field form.total 'value' to  %}
                    </div>


                    <div class="form-group">
                        <label for="description" id="discount_l">Discount </label>
                        {% crispy_field form.discount %}
                    </div>

                    <div class="form-group">
                        <label for="description" id="gst_l">SGST </label>
                        {% crispy_field form.gst %}
                    </div>
                    <div class="form-group">
                        <label for="description" id="cgst_l">CGST </label>
                        {% crispy_field form.cgst %}
                    </div>


                    <div class="form-group">
                        <label for="description" >
                            Net Amount
                        </label>
                        {% crispy_field form.net_amount 'value' to  %}
                    </div>


                    <div class="form-group" >
                        <label for="description"> Due amount</label>
                            {% crispy_field form.due_amount 'value' to  %}
                    </div>



            </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col">
               <div class="card card-primary">
                      <div class="card-header">
                        <h3 class="card-title">Product View </h3>
                      </div>
                      <div class="card-body">
                        <div class="form-group">
                                    {% include "productin/prodcutin_list.html" %}
                        </div>
                      </div>
               </div>
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}
{% block extra_js %}
    <script>
      document.addEventListener('DOMContentLoaded',function(){
          document.querySelector("#id_total").value={{ to }};
          document.querySelector("#id_net_amount").value={{ to }};
          document.querySelector("#id_due_amount").value={{ to }};

          document.querySelector("#id_gst").focusout=function(){
              let gst=document.querySelector("#id_gst").value;
              document.querySelector("#gst_l").innerHTML=` SGST ${gst}%`;
              let total_amount= parseFloat(document.querySelector("#id_total").value);
              let r =parseFloat(document.querySelector("#id_gst").value=(gst*total_amount)/100);
              let discount = parseFloat(document.querySelector("#id_discount").value);
              let cgst = parseFloat(document.querySelector("#id_cgst").value);
              document.querySelector("#id_net_amount").value =Math.round(total_amount-discount+r+cgst)
              document.querySelector("#id_due_amount").value=Math.round(total_amount-discount+r+cgst)
          }
          document.querySelector("#id_cgst").focusout=function(){
              let cgst=document.querySelector("#id_cgst").value;
              document.querySelector("#cgst_l").innerHTML=` CGST ${cgst}%`;
              let total_amount=parseFloat(document.querySelector("#id_total").value);
              let r = parseFloat(document.querySelector("#id_cgst").value=(cgst*total_amount)/100);
              let gst = parseFloat(document.querySelector("#id_gst").value);
              let discount = parseFloat(document.querySelector("#id_discount").value);
              document.querySelector("#id_net_amount").value= Math.round(total_amount-discount+r+gst)
              document.querySelector("#id_due_amount").value=Math.round(total_amount-discount+r+gst)
          }
          // for inward purchase discount
          document.querySelector("#id_discount").focusout=function(){

              let discount=document.querySelector("#id_discount").value;
              document.querySelector("#discount_l").innerHTML=` Discount ${discount}%`;
              let total_amount=parseFloat(document.querySelector("#id_total").value);
              let r =parseFloat(document.querySelector("#id_discount").value=(discount*total_amount)/100);
              let cgst=parseFloat(document.querySelector("#id_cgst").value);
              let gst = parseFloat(document.querySelector("#id_gst").value);
              document.querySelector("#id_net_amount").value=Math.round(total_amount+cgst+gst-r)
              document.querySelector("#id_due_amount").value=Math.round(total_amount+cgst+gst-r)
          }
      })
      {#document.querySelector("#id_total").disabled = true;#}
      {#document.querySelector("#id_net_amount").disabled = true;#}
      {#document.querySelector("#id_due_amount").disabled = true;#}
    </script>


{% endblock %}